### ISSUE TITLE
Disable adding instance name prefix on child resource name

### ISSUE THREAD

**Issue by jlandowner** [cosmo-workspace/cosmo#171]
Example use case

```yaml
apiVersion: cosmo.cosmo-workspace.github.io/v1alpha1
kind: Template
metadata:
  annotations:
    cosmo/disable-nameprefix: "true"   <--- NEW OPTION
  labels:
    cosmo/type: user-addon
  name: eks-irsa
spec:
  rawYaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/IAM_ROLE_NAME
      name: default    <--- NOT TO BE FIXED
      namespace: '{{NAMESPACE}}'
```
