### ISSUE TITLE
Update LDAP authentication to use search filter

### ISSUE THREAD

**Issue by jlandowner** [cosmo-workspace/cosmo#764]
There are example user authentication code in go-ldap docs.

https://pkg.go.dev/github.com/go-ldap/ldap#example-package-UserAuthentication

```go
// The username and password we want to check
username := "someuser"
password := "userpassword"

bindusername := "readonly"
bindpassword := "password"

l, err := Dial("tcp", fmt.Sprintf("%s:%d", "ldap.example.com", 389))
if err != nil {
	log.Fatal(err)
}
defer l.Close()

// Reconnect with TLS
err = l.StartTLS(&tls.Config{InsecureSkipVerify: true})
if err != nil {
	log.Fatal(err)
}

// First bind with a read only user
err = l.Bind(bindusername, bindpassword)
if err != nil {
	log.Fatal(err)
}

// Search for the given username
searchRequest := NewSearchRequest(
	"dc=example,dc=com",
	ScopeWholeSubtree, NeverDerefAliases, 0, 0, false,
	fmt.Sprintf("(&(objectClass=organizationalPerson)(uid=%s))", username),
	[]string{"dn"},
	nil,
)

sr, err := l.Search(searchRequest)
if err != nil {
	log.Fatal(err)
}

if len(sr.Entries) != 1 {
	log.Fatal("User does not exist or too many entries returned")
}

userdn := sr.Entries[0].DN

// Bind as the user to verify their password
err = l.Bind(userdn, password)
if err != nil {
	log.Fatal(err)
}

// Rebind as the read only user for any further queries
err = l.Bind(bindusername, bindpassword)
if err != nil {
	log.Fatal(err)
}

```

values.yaml might be like this (?)

```yaml
auth:
  ldap:
    enabled: false
    url: "ldap://example.com:389"
    # baseDn is a base DN for 
    baseDn: "dc=example,dc=com"
    # userAttr is an ldap user attribute to bind directly or key to distinguish user in search
    userAttr: "sAMAccountname"
    search:
      # bindDn is a searcher's user DN
      bindDn: "uid=tesla,dc=example,dc=com"
      # bindPassword is a password for searcher
      bindPassword: password
      # filter is a search filter pattern to find a user to to authenticated
      filter: "(&(objectClass=person)({{.UserAttr}}={{.Username}}))"
    tls:
      insecure: false
      secretName: ""
      startTls: false
```
