### ISSUE TITLE
Move cosmo-traefik-plugins into cosmo-controller-manager

### ISSUE THREAD

**Issue by jlandowner** [cosmo-workspace/cosmo#835]
Currently, when using private registry, we have to change the whole configuration of traefik init containers in values file.

```yaml
traefik:
  deployment:
    # Installing local plugins by init containers
    initContainers:
      - name: copy-plugins
        image: ghcr.io/cosmo-workspace/cosmo-traefik-plugins:latest # <----- here
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "cp -r /plugins-local/* /local-plugins/"]
        volumeMounts:
          - name: local-plugins
            mountPath: /local-plugins
```

Bundle cosmo-traefik-plugins into controller manager and download it in the cluster.
